openapi: 3.0.1
info:
  title: OQTOPUS Cloud Provider API
  version: '1.0'
  contact:
    name: oqtopus-team
    email: oqtopus-team[at]googlegroups.com
  description: OQTOPUS Cloud Provider API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8888
    description: Local server url
security:
  - ApiKeyAuth: []
paths:
  /devices/{device_id}:
    patch:
      tags:
        - devices
      summary: Update a part of selected device's properties.
      description: Update a part of selected device's properties.
      operationId: patchDevice
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: device_id
          description: Device ID
          required: true
          schema:
            type: string
            example: Kawasaki
      requestBody:
        description: Chagens to the specified device.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/devices.UpdateDeviceRequest'
      responses:
        '200':
          description: Device is updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/devices.UpdateDeviceResponse'
              example:
                message: Device is successfully updated
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                message: Bad request malformed input data
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: Device not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
              example:
                message: Internal server error
  /devices/{device_id}/status:
    patch:
      tags:
        - devices
      summary: Update status of selected device
      description: Update status of selected device.
      operationId: patchDeviceStatus
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: device_id
          description: Device ID
          required: true
          schema:
            type: string
            example: Kawasaki
      requestBody:
        description: 'New device status. '
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/devices.DeviceStatusUpdate'
      responses:
        '200':
          description: Device's data updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/devices.DeviceDataUpdateResponse'
              example:
                message: Device's data updated
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                message: Bad request malformed input data
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: Device not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
              example:
                message: Internal server error
  /devices/{device_id}/device_info:
    patch:
      tags:
        - devices
      summary: Update device_info(calibration data) of selected device
      description: Update device_info(calibration data) of selected device.
      operationId: patchDeviceInfo
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: device_id
          description: Device ID
          required: true
          schema:
            type: string
            nullable: false
            example: Kawasaki
      requestBody:
        description: 'New device info. '
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/devices.DeviceInfoUpdate'
      responses:
        '200':
          description: Device's data updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/devices.DeviceDataUpdateResponse'
              example:
                message: Device's data updated
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                message: Bad request malformed input data
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: Device not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
              example:
                message: Internal server error
  /jobs:
    get:
      tags:
        - jobs
      summary: Search jobs for a device
      description: Search jobs for a device
      operationId: get_jobs
      parameters:
        - in: query
          name: device_id
          required: true
          description: Device identifier
          schema:
            type: string
            nullable: false
            example: Kawasaki
        - in: query
          name: status
          required: false
          description: Additional search parameter:<br/> Search jobs with specified status only
          schema:
            $ref: '#/components/schemas/jobs.JobStatus'
        - name: fields
          in: query
          description: |-
            Allows to specify an exact list of job properties to fetch for a single job. Each element of the list must be a valid name of job property.

            If parameter is specified and requested job field is not defined for a job null is returned.

            If parameter is omitted all available job properties are returned.
          required: false
          schema:
            type: string
            maxLength: 1024
            example: job_id,status,name
        - in: query
          name: limit
          required: false
          description: Additional search parameter:<br/> Set max number of quantum jobs to return in single request
          schema:
            type: integer
            nullable: false
            example: 1
        - in: query
          name: timestamp
          description: Additional search parameter:<br/> Jobs created after the specified timetsamp
          schema:
            type: string
            format: date-time
            example: '2022-12-15T15:54:46Z'
      responses:
        '200':
          description: List of jobs for a device
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/jobs.Job'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                message: Bad request malformed input data
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
              example:
                message: Internal server error
  /jobs/{job_id}:
    get:
      summary: Get a job by ID
      description: Get a job by ID
      operationId: get_job
      tags:
        - jobs
      parameters:
        - in: path
          name: job_id
          required: true
          description: Job identifier
          schema:
            type: string
            nullable: false
      responses:
        '200':
          description: Return quantum job
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs.JobDef'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                message: Bad request malformed input data
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: job not found
  /jobs/{job_id}/upload:
    get:
      summary: Get presigned URLs for upload
      description: Get presigned URLs for job information items upload
      operationId: get_upload
      tags:
        - jobs
      parameters:
        - name: job_id
          in: path
          required: true
          description: Job identifier
          schema:
            type: string
            nullable: false
        - name: items
          in: query
          required: true
          description: |-
            A list of job information items to upload

            Available job information items are: `combined_program`, `transpile_result`, `result`, `sse_log`
          schema:
            type: string
            maxLength: 1024
            example: result,sse_log
      responses:
        '200':
          description: Return the list of presigned URL data for upload, arranged in the order specified by the items parameter.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/jobs.JobInfoUploadPresignedURL'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                message: Bad request malformed input data
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: job not found
  /jobs/{job_id}/status:
    patch:
      summary: Update job status
      description: Update job status and status related data
      operationId: patch_job
      tags:
        - jobs
      parameters:
        - in: path
          name: job_id
          required: true
          description: Job identifier
          schema:
            type: string
            nullable: false
      requestBody:
        description: New job status and status related data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jobs.JobStatusUpdate'
      responses:
        '200':
          description: job data updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs.JobStatusUpdateResponse'
              example:
                message: job data updated
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: Job not found
        '409':
          description: Returned when the specified job is not in a status that allows transition to the requested status.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.ConflictError'
              example:
                message: The specified job is not in a status that allows transition to the requested status.
  /jobs/{job_id}/transpiler_info:
    put:
      summary: Overwrite selected quantum job's traspiler_info
      description: |
        Overwrite selected quantum job's transpiler_info.
      operationId: update_job_transpiler_info
      tags:
        - jobs
      parameters:
        - in: path
          name: job_id
          required: true
          description: Job identifier
          schema:
            type: string
            nullable: false
      requestBody:
        description: Modifications applied to transpiler info
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/jobs.UpdateJobTranspilerInfoRequest'
      responses:
        '200':
          description: job info updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs.UpdateJobTranspilerInfoResponse'
              example:
                message: Job info updated.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.BadRequest'
              example:
                message: Bad request malformed input data
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.NotFoundError'
              example:
                message: Job not found
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
  schemas:
    jobs.S3SubmitJobInfo:
      type: object
      properties:
        program:
          type: array
          description: A list of OPENQASM3 program. Required for sampling, estimation and multiprogramming jobs. For non-multiprogramming jobs, this field is assumed to contain exactly one program. Otherwise, those programs are combined according to the multiprogramming machinery.
          items:
            type: string
          example:
            - OPENQASM 3; qubit[2] q; bit[2] c; h q[0]; cnot q[0], q[1]; c = measure q;
        operator:
          type: array
          items:
            $ref: '#/components/schemas/jobs.S3OperatorItem'
          description: Estimation operator. Required for estimation jobs.
        sse_program:
          type: string
          description: SSE user program. Required for SSE jobs.
    jobs.S3JobResult:
      type: object
      nullable: true
      properties:
        sampling:
          $ref: '#/components/schemas/jobs.S3SamplingResult'
        estimation:
          $ref: '#/components/schemas/jobs.S3EstimationResult'
      additionalProperties: true
      required: []
    jobs.S3TranspileResult:
      type: object
      nullable: true
      properties:
        transpiled_program:
          type: string
          nullable: true
          example: OPENQASM 3; include "stdgates.inc"; qubit[2] _all_qubits; let q = _all_qubits[0:1]; h q[0]; cx q[0], q[1];
        stats:
          type: object
          properties: {}
          additionalProperties: true
          nullable: true
        virtual_physical_mapping:
          type: object
          properties: {}
          additionalProperties: true
          nullable: true
      required:
        - transpiled_program
        - stats
        - virtual_physical_mapping
    devices.UpdateDeviceRequest:
      type: object
      properties:
        n_qubits:
          type: integer
          nullable: true
    devices.UpdateDeviceResponse:
      type: object
      properties:
        message:
          type: string
          nullable: false
          default: Device is successfully updated.
          example: Device is successfully updated.
      required:
        - message
    error.BadRequest:
      type: object
      properties:
        message:
          type: string
          nullable: false
      required:
        - message
    error.NotFoundError:
      type: object
      properties:
        message:
          type: string
          nullable: false
      required:
        - message
    error.InternalServerError:
      type: object
      properties:
        message:
          type: string
          nullable: false
      required:
        - message
    devices.DeviceStatusUpdate:
      type: object
      properties:
        status:
          type: string
          enum:
            - available
            - unavailable
          nullable: false
      required:
        - status
    devices.DeviceDataUpdateResponse:
      type: object
      properties:
        message:
          type: string
          nullable: false
          default: Device data updated
          example: Device data updated
      required:
        - message
    devices.DeviceInfoUpdate:
      type: object
      properties:
        device_info:
          description: Calibration_data and n_nodes etc. Make sure that the value is a valid JSON data.
          type: string
          nullable: true
          example: |-
            {
              "n_nodes": 512,
              "calibration_data": {
                "qubit_connectivity": [
                  "(1,4)",
                  "(4,5)",
                  "(5,8)"
                ],
                "t1": {
                  "0": 55.51,
                  "1": 37.03,
                  "2": 57.13
                }
              }
            }
        calibrated_at:
          description: Parameter mandatory and valid if calibrationData not null
          type: string
          format: date-time
          example: '2023-09-10T14:00:00Z'
          nullable: true
      required:
        - device_info
    jobs.JobStatus:
      type: string
      enum:
        - submitted
        - ready
        - running
        - succeeded
        - failed
        - cancelled
      example: submitted
    jobs.JobId:
      type: string
      example: 7af020f6-2e38-4d70-8cf0-4349650ea08c
    jobs.JobType:
      type: string
      enum:
        - sampling
        - estimation
        - multi_manual
        - sse
    jobs.JobInfoDownloadPresignedURL:
      description: Presigned URL for downloading a file from OCTOPUS cloud.
      type: string
      nullable: false
      example: https://oqtopus-cloud.s3.amazonaws.com/jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/filename.zip?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1714425600&Signature=abc123def456ghi789jkl%2Fsignature%3D
    jobs.Job:
      type: object
      properties:
        job_id:
          $ref: '#/components/schemas/jobs.JobId'
          nullable: false
        name:
          type: string
          example: Bell State Sampling
          nullable: true
        description:
          type: string
          example: Bell State Sampling Example
          nullable: false
        job_type:
          $ref: '#/components/schemas/jobs.JobType'
          nullable: false
        device_id:
          type: string
          example: Kawasaki
          nullable: false
        shots:
          type: integer
          minimum: 1
          maximum: 10000000
          example: 1000
          nullable: false
        input:
          $ref: '#/components/schemas/jobs.JobInfoDownloadPresignedURL'
          nullable: false
        transpiler_info:
          type: object
          nullable: true
          properties: {}
          additionalProperties: true
          example:
            qubit_allocation:
              '0': 12
              '1': 16
            skip_transpilation: false
            seed_transpilation: 873
        simulator_info:
          type: object
          properties: {}
          additionalProperties: true
          nullable: true
          example:
            n_qubits: 5
            n_nodes: 12
            n_per_node: 2
            seed_simulation: 39058567
            simulation_opt:
              optimization_method: light
              optimization_block_size: 1
              optimization_swap_level: 1
        mitigation_info:
          type: object
          properties: {}
          additionalProperties: true
          example:
            ro_error_mitigation: pseudo_inverse
          nullable: true
        status:
          $ref: '#/components/schemas/jobs.JobStatus'
          nullable: false
        execution_time:
          type: number
          example: 10.123
          nullable: true
          default: null
        submitted_at:
          type: string
          format: date-time
          nullable: true
          default: null
          example: '2022-10-19T11:45:34Z'
        ready_at:
          type: string
          format: date-time
          nullable: true
          default: null
          example: '2022-10-19T11:45:34Z'
        running_at:
          type: string
          format: date-time
          nullable: true
          default: null
          example: '2022-10-19T11:45:34Z'
        ended_at:
          type: string
          format: date-time
          example: '2022-10-19T11:45:34Z'
          nullable: true
          default: null
      required: []
      example:
        job_id: 7af020f6-2e38-4d70-8cf0-4349650ea08c
        name: Bell State Sampling
        description: Bell State Sampling Example
        device_id: Kawasaki
        job_type: sampling
        input: https://oqtopus-cloud.s3.amazonaws.com/jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/input.zip?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1714425600&Signature=abc123def456ghi789jkl%2Fsignature%3D
        transpiler_info:
          qubit_allocation:
            '0': 12
            '1': 16
          skip_transpilation: false
          seed_transpilation: 873
        simulator_info:
          n_qubits: 5
          n_nodes: 12
          n_per_node: 2
          seed_simulation: 39058567
          simulation_opt:
            optimization_method: light
            optimization_block_size: 1
            optimization_swap_level: 1
        mitigation_info:
          ro_error_mitigation: pseudo_inverse
        shots: 1000
        status: submitted
        execution_time: 10.123
        submitted_at: '2022-10-19T11:45:34Z'
        ready_at: '2022-10-19T11:45:34Z'
        running_at: '2022-10-19T11:45:34Z'
        ended_at: '2022-10-19T11:45:34Z'
    jobs.JobDef:
      allOf:
        - $ref: '#/components/schemas/jobs.Job'
      required:
        - job_id
        - device_id
        - job_type
        - input
        - shots
        - status
    jobs.JobInfoUploadPresignedURL:
      description: Presigned URL for uploading file to OCTOPUS cloud.
      type: object
      properties:
        url:
          type: string
          example: https://oqtopus-cloud.s3.amazonaws.com/
        fields:
          type: object
          properties:
            key:
              type: string
              example: jobs/7af020f6-2e38-4d70-8cf0-4349650ea08c/filename.zip
            AWSAccessKeyId:
              type: string
            x-amz-security-token:
              type: string
            policy:
              type: string
            signature:
              type: string
    jobs.JobStatusUpdate:
      type: object
      properties:
        status:
          type: string
          enum:
            - running
            - succeeded
            - failed
            - cancelled
          example: succeeded
          nullable: false
        output_files:
          description: List of all S3 file keys uploaded by provider during job execution.
          type: array
          items:
            type: string
          nullable: true
          example:
            - 7af020f6-2e38-4d70-8cf0-4349650ea08c/combined_program.zip
            - 7af020f6-2e38-4d70-8cf0-4349650ea08c/transpile_result.zip
            - 7af020f6-2e38-4d70-8cf0-4349650ea08c/result.zip
        message:
          type: string
          nullable: true
          example: Execution successful
        execution_time:
          type: number
          description: Execution time for quantum computation. Specify the time in seconds, including up to milliseconds.
          nullable: true
          example: 1256.58
      required:
        - status
    jobs.JobStatusUpdateResponse:
      type: object
      properties:
        message:
          type: string
          nullable: false
      required:
        - message
    error.ConflictError:
      type: object
      properties:
        message:
          type: string
          nullable: false
      required:
        - message
    jobs.UpdateJobTranspilerInfoRequest:
      type: object
      properties: {}
      additionalProperties: true
    jobs.UpdateJobTranspilerInfoResponse:
      type: object
      properties:
        message:
          type: string
          nullable: false
      required:
        - message
    jobs.S3OperatorItem:
      type: object
      properties:
        pauli:
          type: string
          description: The Pauli string.
          nullable: false
          example: X 0 X 1
        coeff:
          description: Coefficient number in the Pauli string representation.
          type: number
      required:
        - pauli
    jobs.S3SamplingResult:
      type: object
      nullable: true
      description: '*(Only for sampling jobs)* JSON string representing the sampling result'
      properties:
        counts:
          type: object
          nullable: false
          properties: {}
          additionalProperties: true
          example:
            '10': 84
            '11': 387
            '00': 454
            '01': 75
        divided_counts:
          type: object
          nullable: true
          properties: {}
          additionalProperties: true
          example:
            '0':
              '10': 454
              '11': 387
              '00': 84
              '01': 75
            '1':
              '10': 454
              '11': 387
              '00': 84
              '01': 75
      required:
        - counts
    jobs.S3EstimationResult:
      type: object
      nullable: true
      description: |
        *(Only for estimation jobs)* The estimated expectation value and the standard deviation
        of the operators specified in `job_info.operator` field which is intended to be provided for estimation jobs.
      properties:
        exp_value:
          description: The estimated expection value.
          nullable: false
          type: number
        stds:
          description: The standard deviation value
          nullable: false
          type: number
      required:
        - exp_value
        - stds
